# Generated by Django 5.0.2 on 2024-02-09 04:22

import django.db.models.deletion
import django.db.models.functions.datetime
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portfolioName",
                    models.CharField(max_length=20, verbose_name="Portfolio Name"),
                ),
                ("portfolioDescription", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name_plural": "Portfolios",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(auto_now=True, verbose_name="Transaction Date"),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="Symbol")),
                (
                    "type",
                    models.CharField(
                        default="B", max_length=2, verbose_name="Transaction Type"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[main.models.validate_zero],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[main.models.validate_zero],
                        verbose_name="Price",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[main.models.validate_zero],
                        verbose_name="BrokerageCost",
                    ),
                ),
                (
                    "portfolioId",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("transaction_date__gt", django.db.models.functions.datetime.Now())
                ),
                name="Date cannot be in future!!",
            ),
        ),
    ]
